tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "homebrew/services"
tap "teamookla/speedtest"
brew "asdf"
brew "blueutil"
brew "pkg-config"
brew "gawk"
brew "gcc"
brew "ghq"
brew "git"
brew "git-secrets"
brew "gnupg"
brew "gradle"
brew "icu4c"B
brew "graphviz"
brew "grep"
brew "helm"
brew "kubectx"
brew "mysql", restart_service: true
brew "peco"
brew "php", restart_service: true
brew "plantuml"
brew "postgresql", restart_service: true
brew "rsync"
brew "tflint"
brew "tmux"
brew "tree"
brew "wget"
brew "zsh-completions"
brew "heroku/brew/heroku"
brew "teamookla/speedtest/speedtest"
cask "alacritty"
cask "font-migu-1p"
